FROM coscupweb-base:24.04.25

ADD ./setting.py \
    ./uwsgi.ini \
    ./main.py \
    ./

ADD ./cmdtools/*.py ./cmdtools/

ADD ./celery_task/__init__.py \
    ./celery_task/celery_main.py \
	./celery_task/task*.py \
	./celery_task/

ADD ./models/__init__.py \
    ./models/api_tokendb.py \
    ./models/base.py \
    ./models/budgetdb.py \
    ./models/dispensedb.py \
    ./models/expensedb.py \
    ./models/formdb.py \
    ./models/index.py \
    ./models/mailletterdb.py \
    ./models/mattermost_link_db.py \
    ./models/mattermostdb.py \
    ./models/oauth_db.py \
    ./models/projectdb.py \
    ./models/senderdb.py \
    ./models/tasksdb.py \
    ./models/teamdb.py \
    ./models/telegram_db.py \
    ./models/trackdb.py \
    ./models/users_db.py \
    ./models/usessiondb.py \
    ./models/waitlistdb.py \
    ./models/

ADD ./module/__init__.py \
    ./module/api_token.py \
    ./module/awsses.py \
    ./module/budget.py \
    ./module/dietary_habit.py \
    ./module/dispense.py \
    ./module/expense.py \
    ./module/form.py \
    ./module/gitlab_api.py \
    ./module/gsuite.py \
    ./module/ipinfo.py \
    ./module/mattermost_bot.py \
    ./module/mattermost_link.py \
    ./module/mc.py \
    ./module/oauth.py \
    ./module/project.py \
    ./module/project_working.py \
    ./module/sender.py \
    ./module/service_sync.py \
    ./module/skill.py \
    ./module/tasks.py \
    ./module/team.py \
    ./module/telegram_bot.py \
    ./module/track.py \
    ./module/users.py \
    ./module/usession.py \
    ./module/waitlist.py \
    ./module/

ADD ./templates/base.html \
    ./templates/budget.html \
    ./templates/budget_batch.html \
    ./templates/bug_report.html \
    ./templates/coc* \
    ./templates/dev*.html \
    ./templates/expense.html \
    ./templates/expense_lists.html \
    ./templates/expense_menu.html \
    ./templates/expense_my.html \
    ./templates/form*.html \
    ./templates/guide_index.html \
    ./templates/index.html \
    ./templates/index_guide.html \
    ./templates/privacy* \
    ./templates/project*.html \
    ./templates/recruit_list.html \
    ./templates/schedule* \
    ./templates/security_guard* \
    ./templates/sender*.html \
    ./templates/setting*.html \
    ./templates/tasks*.html \
    ./templates/team*.html \
    ./templates/user.html \
    ./templates/

ADD ./static/ExpenseStatusLabel.js \
    ./static/ExpenseTable.js \
    ./static/ExpenseEditor.js \
    ./static/DispenseEditor.js \
    ./static/DispenseTable.js \
    ./static/InvoiceList.js \
    ./static/UserBadge.js \
    ./static/expense-component.css \
    ./static/forms.css \
    ./static/buefy.min.js \
    ./static/buefy.min.css \
    ./static/dayjs.min.js \
    ./static/

ADD ./templates/mail/base*.html \
    ./templates/mail/coscup_base.html \
    ./templates/mail/sender_base.html \
    ./templates/mail/tasks_star.html \
    ./templates/mail/welcome.html \
    ./templates/mail/

ADD ./view/__init__.py \
    ./view/api.py \
    ./view/budget.py \
    ./view/dev.py \
    ./view/dispense.py \
    ./view/expense.py \
    ./view/guide.py \
    ./view/links.py \
    ./view/project.py \
    ./view/recruit.py \
    ./view/schedule.py \
    ./view/sender.py \
    ./view/setting.py \
    ./view/tasks.py \
    ./view/team.py \
    ./view/telegram.py \
    ./view/user.py \
    ./view/utils.py \
    ./view/

ADD ./structs/__init__.py \
    ./structs/projects.py \
    ./structs/tasks.py \
    ./structs/teams.py \
    ./structs/users.py \
    ./structs/

ADD ./api/__init__.py \
    ./api/dependencies.py \
    ./api/main.py \
    ./api/

ADD ./api/apistructs/__init__.py \
    ./api/apistructs/items.py \
    ./api/apistructs/members.py \
    ./api/apistructs/projects.py \
    ./api/apistructs/sender.py \
    ./api/apistructs/tasks.py \
    ./api/apistructs/teams.py \
    ./api/apistructs/users.py \
    ./api/apistructs/

ADD ./api/routers/__init__.py \
    ./api/routers/members.py \
    ./api/routers/projects.py \
    ./api/routers/sender.py \
    ./api/routers/tasks.py \
    ./api/routers/teams.py \
    ./api/routers/user.py \
    ./api/routers/

ADD ./docs_dev/ ./docs_dev/

RUN apk add git
RUN git config --global user.email "volunteer@coscup.org"
RUN git config --global user.name "COSCUP Volunteer"
RUN git init
RUN git add .
RUN git commit -m 'init'
