FROM volunteer-base:20.06.16

ADD ./privacy.md ./privacy.md
ADD ./celery_task ./celery_task
ADD ./client_secret.json ./client_secret.json
ADD ./secretary-e00794553a7d.json ./secretary-e00794553a7d.json
ADD ./main.py ./main.py
ADD ./models ./models
ADD ./module ./module
ADD ./setting.py ./setting.py
ADD ./templates ./templates
ADD ./view ./view
