FROM volunteer-base:21.02.27

ADD ./client_secret.json ./client_secret.json
ADD ./privacy.md ./privacy.md
ADD ./secretary-e00794553a7d.json ./secretary-e00794553a7d.json
ADD ./setting.py ./setting.py

ADD ./celery_task/celery.py ./celery_task/celery.py
ADD ./celery_task/task*.py ./celery_task/

ADD ./models/base.py ./models/base.py
ADD ./models/formdb.py ./models/formdb.py
ADD ./models/index.py ./models/index.py
ADD ./models/mailletterdb.py ./models/mailletterdb.py
ADD ./models/mattermost_link_db.py ./models/mattermost_link_db.py
ADD ./models/mattermostdb.py ./models/mattermostdb.py
ADD ./models/oauth_db.py ./models/oauth_db.py
ADD ./models/projectdb.py ./models/projectdb.py
ADD ./models/senderdb.py ./models/senderdb.py
ADD ./models/tasksdb.py ./models/tasksdb.py
ADD ./models/teamdb.py ./models/teamdb.py
ADD ./models/users_db.py ./models/users_db.py
ADD ./models/usessiondb.py ./models/usessiondb.py
ADD ./models/waitlistdb.py ./models/waitlistdb.py

ADD ./module/awsses.py ./module/awsses.py
ADD ./module/dietary_habit.py ./module/dietary_habit.py
ADD ./module/form.py ./module/form.py
ADD ./module/gitlab_api.py ./module/gitlab_api.py
ADD ./module/gsuite.py ./module/gsuite.py
ADD ./module/ipinfo.py ./module/ipinfo.py
ADD ./module/mattermost_bot.py ./module/mattermost_bot.py
ADD ./module/mattermost_link.py ./module/mattermost_link.py
ADD ./module/mc.py ./module/mc.py
ADD ./module/oauth.py ./module/oauth.py
ADD ./module/project.py ./module/project.py
ADD ./module/project_working.py ./module/project_working.py
ADD ./module/sender.py ./module/sender.py
ADD ./module/service_sync.py ./module/service_sync.py
ADD ./module/tasks.py ./module/tasks.py
ADD ./module/team.py ./module/team.py
ADD ./module/users.py ./module/users.py
ADD ./module/usession.py ./module/usession.py
ADD ./module/waitlist.py ./module/waitlist.py

ADD ./templates/base.html ./templates/base.html
ADD ./templates/bug_report.html ./templates/bug_report.html
ADD ./templates/form*.html ./templates/
ADD ./templates/guide_index.html ./templates/guide_index.html
ADD ./templates/index.html ./templates/index.html
ADD ./templates/index_guide.html ./templates/index_guide.html
ADD ./templates/privacy.html ./templates/privacy.html
ADD ./templates/project*.html ./templates/
ADD ./templates/sender*.html ./templates/
ADD ./templates/setting*.html ./templates/
ADD ./templates/tasks*.html ./templates/
ADD ./templates/team*.html ./templates/
ADD ./templates/user.html ./templates/user.html

ADD ./templates/mail/base*.html ./templates/mail/
ADD ./templates/mail/coscup_base.html ./templates/mail/coscup_base.html
ADD ./templates/mail/sender_base.html ./templates/mail/sender_base.html
ADD ./templates/mail/tasks_star.html ./templates/mail/tasks_star.html
ADD ./templates/mail/welcome.html ./templates/mail/welcome.html

ADD ./view/api.py ./view/api.py
ADD ./view/guide.py ./view/guide.py
ADD ./view/links.py ./view/links.py
ADD ./view/project.py ./view/project.py
ADD ./view/sender.py ./view/sender.py
ADD ./view/setting.py ./view/setting.py
ADD ./view/tasks.py ./view/tasks.py
ADD ./view/team.py ./view/team.py
ADD ./view/user.py ./view/user.py
ADD ./view/utils.py ./view/utils.py

ADD ./main.py ./main.py
