[tool.poetry]
name = "coscup-volunteer"
version = "2022.05.03"
description = "COSCUP Volunteer 志工服務系統，主要解決招募、人員管理、行政流程建立。"
authors = ["COSCUP Volunteer <volunteer@coscup.org>"]
license = "AGPL-3.0"

[tool.poetry.dependencies]
python = "^3.8"
google-api-python-client = "^2.40.0"
google-auth = "^2.6.0"
google-auth-httplib2 = "^0.1.0"
google-auth-oauthlib = "^0.5.0"
Flask = "^2.0.3"
Markdown = "^3.3.6"
arrow = "^1.2.2"
blinker = "^1.4"
boto3 = "^1.21.18"
celery = "^5"
phonenumbers = "^8.12.45"
pydantic = "^1.9.0"
pylibmc = "^1.6.1"
pymongo = "^4.0.2"
requests = "^2.27.1"
uWSGI = "^2.0.20"

[tool.poetry.dev-dependencies]
mongomock = "^4.0.0"
pylint = "^2.13.8"
autopep8 = "^1.6.0"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
mypy = "^0.950"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# https://docs.pytest.org/en/7.1.x/reference/customize.html#pyproject-toml
[tool.pytest.ini_options]
required_plugins = "pytest-cov"

# https://coverage.readthedocs.io/en/latest/config.html?highlight=pyproject.toml
[tool.coverage.run]
omit = ["setting_sample.py", "setting.py", "tests/*"]

# https://githb.com/PyCQA/isort/wiki/isort-Settings
[tool.isort]
virtual_env = "./venv"
