site_name: COSCUP Volunteer Docs
site_url: https://volunteer.coscup.org/docs/
site_description: "Documentation for users, developers, and team members"
site_author: "COSCUP Secretary Team / 行政組"
repo_url: https://github.com/COSCUP/COSCUP-Volunteer
repo_name: COSCUP/COSCUP-Volunteer
edit_uri: https://github.com/COSCUP/COSCUP-Volunteer/blob/main/docs_dev/docs/
copyright: "CC BY 4.0 2022 COSCUP Volunteer"
nav:
  - Home: index.md
  - Introduction:
    - Overview: intro.md
    - Contributing: contribute.md
  - Developers:
    - Developer Beginner: dev/beginners.md
    - Build Base Image: dev/build-base-image.md
    - Dev Page: dev/dev-page.md
    - Contributing:
      - Contributing on Github: dev/contribute-on-github.md
      - Developer Certificate of Origin (DCO): dev/dco.md
      - How to sign-off commits: dev/how-to-signoff.md
    - API: dev/api.md
    - Code Reference:
      - Overview: code_reference/overview.md
      - Main: code_reference/main.md
      - View: code_reference/view.md
      - Celery Task: code_reference/celery_task.md
      - Models:
        - base: code_reference/models/base.md
        - budgetdb: code_reference/models/budgetdb.md
        - expensedb: code_reference/models/expensedb.md
        - formdb: code_reference/models/formdb.md
        - index: code_reference/models/index.md
        - mailletterdb: code_reference/models/mailletterdb.md
        - mattermost_link_db: code_reference/models/mattermost_link_db.md
        - mattermostdb: code_reference/models/mattermostdb.md
        - oauth_db: code_reference/models/oauth_db.md
        - projectdb: code_reference/models/projectdb.md
        - senderdb: code_reference/models/senderdb.md
        - tasksdb: code_reference/models/tasksdb.md
        - teamdb: code_reference/models/teamdb.md
        - telegram_db: code_reference/models/telegram_db.md
        - users_db: code_reference/models/users_db.md
        - usessiondb: code_reference/models/usessiondb.md
        - waitlistdb: code_reference/models/waitlistdb.md
      - Module:
        - awsses: code_reference/module/awsses.md
        - budget: code_reference/module/budget.md
        - dietary_habit: code_reference/module/dietary_habit.md
        - expense: code_reference/module/expense.md
        - form: code_reference/module/form.md
        - mc: code_reference/module/mc.md
        - oauth: code_reference/module/oauth.md
        - project: code_reference/module/project.md
        - sender: code_reference/module/sender.md
        - service_sync: code_reference/module/service_sync.md
        - skill: code_reference/module/skill.md
        - tasks: code_reference/module/tasks.md
        - users: code_reference/module/users.md
        - usession: code_reference/module/usession.md
        - waitlist: code_reference/module/waitlist.md
        - Third Party API:
          - gitlab_api: code_reference/module/gitlab_api.md
          - gsuite: code_reference/module/gsuite.md
          - ipinfo: code_reference/module/ipinfo.md
          - mattermost: code_reference/module/mattermost.md
          - telegram_bot: code_reference/module/telegram_bot.md
      - Structs:
        - projects: code_reference/structs/projects.md
        - tasks: code_reference/structs/tasks.md
        - teams: code_reference/structs/teams.md
        - users: code_reference/structs/users.md
  - Security: security.md
  - About COSCUP:
    - Team Leader Handbook: about_coscup/team_leader_handbook.md
    - Team Member Handbook: about_coscup/team_member_handbook.md
  - About Secretary Team:
    - Overview: secretary_team/overview.md
    - Recruit: secretary_team/recruit.md
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  language: en
  font:
    text: "Roboto"
    code: "Courier Prime"
  features:
    - content.code.annotate
    - navigation.top
    - search.suggest
extra:
  analytics:
    provider: google
    property: UA-156956691-1
plugins:
  - i18n:
      default_language: en
      default_language_only: false
      docs_structure: suffix
      languages:
        en:
          name: "English (en-US)"
          build: true
        zh_TW:
          name: "臺灣正體 (zh-TW)"
          build: true
      nav_translations:
        zh_TW:
          Home: "首頁"
          Overview: "摘要"
          Introduction: "介紹"
          Developers: "開發者"
          Developer Beginner: "初次開發"
          Contributing: "貢獻"
          Security: "資安通報"
          "About Secretary Team": "關於行政組"
          Recruit: "招募"
          "About COSCUP": "關於 COSCUP"
          "Team Leader Handbook": "組長手冊"
          "Team Member Handbook": "組員手冊"
  - search
  - social:
      cards_font: Noto Sans TC
  - git-revision-date-localized
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_signature_annotations: true
            separate_signature: true
          import:
            - https://boto3.amazonaws.com/v1/documentation/api/latest/objects.inv
            - https://docs.python.org/3/objects.inv
            - https://google-auth-oauthlib.readthedocs.io/en/latest/objects.inv
            - https://google-auth.readthedocs.io/en/stable/objects.inv
            - https://pymongo.readthedocs.io/en/stable/objects.inv
            - https://requests.readthedocs.io/en/master/objects.inv
            - https://sendapatch.se/projects/pylibmc/objects.inv
markdown_extensions:
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - def_list
