site_name: COSCUP Volunteer Docs
site_url: https://volunteer.coscup.org/docs/
site_description: "使用者、開發者與志工夥伴的文件說明 Documentation for users, developers, and team members"
site_author: "COSCUP Secretary Team / 行政組"
repo_url: https://github.com/COSCUP/COSCUP-Volunteer
repo_name: COSCUP/COSCUP-Volunteer
edit_uri: https://github.com/COSCUP/COSCUP-Volunteer/blob/main/docs_dev/docs/
copyright: "CC BY 4.0 2022-2024 COSCUP Volunteer"
nav:
  - Home: index.md
  - Developers:
      - Introduction:
          - Overview: intro.md
          - Contributing: contribute.md
      - Developer Beginner: dev/beginners.md
      - Build Base Image: dev/build-base-image.md
      - Dev Page: dev/dev-page.md
      - Contributing:
          - Contributing on Github: dev/contribute-on-github.md
          - Developer Certificate of Origin (DCO): dev/dco.md
          - How to sign-off commits: dev/how-to-signoff.md
      - API: dev/api.md
      - Code Reference:
          - Overview: code_reference/overview.md
          - Main: code_reference/main.md
          - View: code_reference/view.md
          - Celery Task: code_reference/celery_task.md
          - Models:
              - applyreviewdb: code_reference/models/applyreviewdb.md
              - base: code_reference/models/base.md
              - budgetdb: code_reference/models/budgetdb.md
              - expensedb: code_reference/models/expensedb.md
              - formdb: code_reference/models/formdb.md
              - index: code_reference/models/index.md
              - mailletterdb: code_reference/models/mailletterdb.md
              - mattermost_link_db: code_reference/models/mattermost_link_db.md
              - mattermostdb: code_reference/models/mattermostdb.md
              - oauth_db: code_reference/models/oauth_db.md
              - projectdb: code_reference/models/projectdb.md
              - senderdb: code_reference/models/senderdb.md
              - tasksdb: code_reference/models/tasksdb.md
              - teamdb: code_reference/models/teamdb.md
              - telegram_db: code_reference/models/telegram_db.md
              - users_db: code_reference/models/users_db.md
              - usessiondb: code_reference/models/usessiondb.md
              - waitlistdb: code_reference/models/waitlistdb.md
          - Module:
              - applyreview: code_reference/module/applyreview.md
              - awsses: code_reference/module/awsses.md
              - budget: code_reference/module/budget.md
              - dietary_habit: code_reference/module/dietary_habit.md
              - expense: code_reference/module/expense.md
              - form: code_reference/module/form.md
              - mc: code_reference/module/mc.md
              - oauth: code_reference/module/oauth.md
              - project: code_reference/module/project.md
              - sender: code_reference/module/sender.md
              - service_sync: code_reference/module/service_sync.md
              - skill: code_reference/module/skill.md
              - tasks: code_reference/module/tasks.md
              - users: code_reference/module/users.md
              - usession: code_reference/module/usession.md
              - waitlist: code_reference/module/waitlist.md
              - Third Party API:
                  - gitlab_api: code_reference/module/gitlab_api.md
                  - gsuite: code_reference/module/gsuite.md
                  - ipinfo: code_reference/module/ipinfo.md
                  - mattermost: code_reference/module/mattermost.md
                  - telegram_bot: code_reference/module/telegram_bot.md
          - Structs:
              - projects: code_reference/structs/projects.md
              - tasks: code_reference/structs/tasks.md
              - teams: code_reference/structs/teams.md
              - users: code_reference/structs/users.md
      - Error Note:
          - E001: error_note/e001.md
      - Security: security.md
  - About COSCUP:
      - Team Leader Handbook: about_coscup/team_leader_handbook.md
      - Team Member Handbook: about_coscup/team_member_handbook.md
      - Team Setup: about_coscup/team_setup.md
      - COSCUP Calendar: about_coscup/calendar.md
      - How to Participate in COSCUP:
          - about_coscup/how_to_participate/index.md
          - As Community: about_coscup/how_to_participate/as_community.md
          - As Speaker:
              - As Speaker: about_coscup/how_to_participate/as_speaker.md
              - 2024 Call for Proposals: about_coscup/how_to_participate/2024_cfp.md
      - Email Newsletters:
          - Overview: about_coscup/newsletters/overview.md
          - 2024:
              - 2024/04/23: about_coscup/newsletters/2024/20240423.md
              - 2024/03/15: about_coscup/newsletters/2024/20240315.md
              - 2024/02/28: about_coscup/newsletters/2024/20240228.md
              - 2024/01/18: about_coscup/newsletters/2024/20240118.md
          - 2023:
              - 2023/08/17: about_coscup/newsletters/2023/20230817.md
              - 2023/07/26: about_coscup/newsletters/2023/20230726.md
              - 2023/07/20: about_coscup/newsletters/2023/20230720.md
              - 2023/07/08: about_coscup/newsletters/2023/20230708.md
              - 2023/05/19: about_coscup/newsletters/2023/20230519.md
              - 2023/04/27: about_coscup/newsletters/2023/20230427.md
              - 2023/03/21: about_coscup/newsletters/2023/20230321.md
              - 2023/03/02: about_coscup/newsletters/2023/20230302.md
  - About Secretary Team:
      - Overview: secretary_team/overview.md
      - Recruit: secretary_team/recruit.md
      - Roadmap: secretary_team/roadmap.md
      - Instructions:
          - Overview: secretary_team/instructions/overview.md
          - "Scope of Team": secretary_team/instructions/scope_of_team.md
          - "Process Management": secretary_team/instructions/process_management.md
          - "Writing Documentation": secretary_team/instructions/writing_documentation.md
      - Tasks:
          - "List of Tasks": secretary_team/tasks/overview.md
          - "Accounting System": secretary_team/tasks/accounting_system.md
          - "Enhance Recruitment": secretary_team/tasks/enhance_recruitment.md
          - "Community Volunteers Plan": secretary_team/tasks/community_volunteers_plan.md
  - Global Engagement:
      - Hello World: global_engagement/hello_world.md
      - Post-Event Report:
          - SCaLE21x: global_engagement/scale21x.md
  - Announcement:
      - Review in 2022: announcement/review_in_2022.md
      - PyCon TW Sprints: announcement/pycontw_2023_sprints.md
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  language: en
  font:
    text: "Roboto"
    code: "Noto Sans Mono"
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.tracking
    - search.suggest
    - navigation.footer
    - content.action.view
    - content.action.edit
extra:
  analytics:
    provider: google
    property: G-6B98ZDG12C
  social:
    - icon: material/home
      link: https://volunteer.coscup.org/
    - icon: fontawesome/brands/github
      link: https://github.com/COSCUP/COSCUP-Volunteer
    - icon: fontawesome/solid/users-rectangle
      link: https://volunteer.coscup.org/docs/zh-TW/secretary_team/overview/
extra_css:
  - stylesheets/extra.css
plugins:
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - build: true
          default: true
          locale: en
          name: English (en-US)
        - build: true
          default: false
          locale: zh-TW
          name: 臺灣正體 (zh-TW)
          nav_translations:
            About COSCUP: 關於 COSCUP
            About Secretary Team: 關於行政組
            Accounting System: 財務會計系統
            Announcement: 訊息發佈
            As Community: 身為「開源社群」
            As Speaker: 身為「議題講者」
            Build Base Image: 建立基本映像檔
            COSCUP Calendar: 活動行事曆
            Community Volunteers Plan: 社群志工參與計畫
            Contributing: 貢獻
            Dev Page: 開發設定頁面
            Developer Beginner: 初次開發
            Developers: 志工平台開發
            Email Newsletters: 舊報攤（過往電子報）
            Enhance Recruitment: 招募流程增進計畫
            Error Note: 錯誤訊息
            Global Engagement: 國際交流
            Home: 首頁
            How to Participate in COSCUP: 如何參與、準備 COSCUP
            Instructions: 使用手冊
            Introduction: 介紹
            List of Tasks: 任務列表
            Overview: 摘要
            Post-Event Report: 會後參與報告
            Process Management: 任務流程方式
            Recruit: 招募
            Review in 2022: 2022 回顧
            Roadmap: 路線圖
            Scope of Team: 組任務範圍
            Security: 資安通報
            Tasks: 任務規劃執行
            Team Leader Handbook: 組長手冊
            Team Member Handbook: 組員手冊
            Team Setup: 組別建立與設定
            Writing Documentation: 文件紀錄
  - search:
      pipeline:
        - stemmer
        - stopWordFilter
        - trimmer
      lang:
        - en
        - zh
  - social:
      cards_layout_options:
        font_family: Noto Sans TC
  - git-revision-date-localized
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_signature_annotations: true
            separate_signature: true
          import:
            - https://boto3.amazonaws.com/v1/documentation/api/latest/objects.inv
            - https://docs.python.org/3/objects.inv
            - https://google-auth-oauthlib.readthedocs.io/en/latest/objects.inv
            - https://google-auth.readthedocs.io/en/stable/objects.inv
            - https://pymongo.readthedocs.io/en/stable/objects.inv
            - https://requests.readthedocs.io/en/master/objects.inv
            - https://sendapatch.se/projects/pylibmc/objects.inv
markdown_extensions:
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
