name: BuildImages

on:
  push:
    paths:
      - "Dockerfile-**"
      - ".github/workflows/build_image.yml"
  workflow_dispatch:

jobs:
  docker-dev:
    strategy:
      matrix:
        os: ["ubuntu-20.04", "ubuntu-22.04"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build the base image
        run: docker build -t coscupweb-base:24.01.18 -f ./Dockerfile-base-dev ./
      - name: List images
        run: docker images
      - name: Rename sample setting file
        run: mv ./setting_sample.py ./setting.py
      - name: Build app
        run: docker build --no-cache=true -t volunteer-app:prod -f ./Dockerfile-app-dev ./
      - name: List images
        run: docker images
