name: DockerCompose

on:
  push:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List images
        run: docker images
      - name: Rename sample setting file
        run: mv ./setting_sample.py ./setting.py
      - name: Build the base image
        run: docker build -t coscupweb-base:22.06.13 -f ./Dockerfile-base-dev ./
      - name: UP
        run: docker compose up --build --detach
      - name: List images
        run: docker images
      - name: List container
        run: docker ps -a
      - name: Cat Celery Log
        run: |
          sleep 45 ;
          ls -alh ;
          ls -alh ./logs ;
          ls -alh ./logs/workers ;
          cat ./logs/workers/log.log
