name: DockerCompose

on:
  push:
    paths:
      - 'Dockerfile-**'
      - 'docker-compose.yml'
      - '.github/workflows/docker-compose.yml'
    branches:
      - 'code-style'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List images
        run: docker images
      - name: Rename sample setting file
        run: mv ./setting_sample.py ./setting.py
      - name: UP
        run: docker-compose up -d
      - name: List images
        run: docker images
      - name: List container
        run: docker ps -a
      - name: Cat Celery Log
        run: cat ./logs/workers/log.log
