name: DockerCompose

on:
  push:
    paths:
      - 'Dockerfile-**'
      - 'docker-compose.yml'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List images
        run: docker images
      - name: Rename sample setting file
        run: mv ./setting_sample.py ./setting.py
      - name: UP
        run: docker-compose up
      - name: List images
        run: docker images
