name: Pytest

on:
  push:
  workflow_dispatch:

jobs:
  run_test:
    runs-on: ['ubuntu-20.04', 'ubuntu-22.04']
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install memcached libs
        run: sudo apt-get install ca-certificates libmemcached-dev
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.14
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true
      - name: Install dependencies
        run: poetry install
      - name: Create setting.py
        run: mv setting_sample.py setting.py
      - name: Run mypy
        run: PYTHONPATH=./ poetry run mypy ./models/ ./module/
      - name: Run Testing
        run: PYTHONPATH=./ poetry run pytest -vv --cov-report=term-missing --cov ./
      - name: Run Pylint
        run: PYTHONPATH=./ poetry run pylint ./module/
